name: scannutplus
description: "A new Flutter project."
publish_to: "none"
version: 2.2.6+11

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Icons
  cupertino_icons: ^1.0.8

  # Pilar 0 & I18n
  intl: ^0.20.2

  # Biometria
  local_auth: ^2.1.6

  # Backend & Database
  supabase_flutter:
  objectbox: ^4.0.0
  objectbox_flutter_libs: ^4.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # PDF & Printing
  pdf:
  printing:
  path_provider:
  flutter_riverpod: 2.6.1
  google_fonts: ^8.0.0
  shared_preferences: ^2.5.4
  image_picker: ^1.2.1
  lucide_icons: ^0.257.0
  package_info_plus: ^9.0.0
  path: ^1.9.0
  url_launcher: ^6.3.2
  google_generative_ai: any
  flutter_dotenv: ^6.0.0
  flutter_image_compress: ^2.4.0
  http: ^1.6.0
  speech_to_text: ^7.0.0-beta.1
  permission_handler: ^11.3.0
  uuid: ^4.3.3
  google_maps_flutter: ^2.14.0
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  file_picker: ^10.3.10
  just_audio: ^0.10.5
  video_player: ^2.8.2
  video_thumbnail: ^0.5.3
  flutter_markdown: ^0.7.3
  gal: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.8
  objectbox_generator: ^4.0.0
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/.env
    - assets/config.json
    - assets/images/

rules:
  - unused_element
  - unused_local_variable
  - unused_import
  - unused_field
